# controller_list:
#   - name: rm_75
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: True
#     joints:
#       - joint7
#       - joint1
#       - joint2
#       - joint3
#       - joint4
#       - joint5
#       - joint6
#   - name: dh_gripper
#     action_ns: gripper_action
#     type: GripperCommand
#     default: True
#     joints:
#       - finger_joint
# initial:  # Define initial robot poses per group
#   - group: cobot_arm
#     pose: zero